spring:
  application:
    name: java_learning_project
  profiles: test
  boot:
    admin:
      url: http://ali-hz-hbase-name-treeNode:12309
      username: mobvoi
      password: mobvoi
  gson:
    converter:
      enable: false
#      client:
#        service-url: http://testHost:50000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#配置Controller的错误拦截如果不用Jersey的话
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#  data:
#    mongodb:
#      uri: mongodb://useradmin:123456@ec2-54-159-208-93.compute-1.amazonaws.com:27017/test

#redis:
#  list:
#    common:
#      timeout: 5000
#      connection: 127.0.0.1:6379
#      pool:
#        maxTotal: 1024
#        maxIdle: 200
#        minIdle: 20
#        maxWaitMillis: 1000
#        testOnBorrow: true

server:
  port: 9000

#elasticsearch:
#  clusterName: test
#  nodes:
#    - 127.0.0.1:9300

redis:
  name: common
  connection: 127.0.0.1:6379
  password: igTuujYzZSSVd75X

#hbase:
#  quorum: 127.0.0.1
#  port: 2181

kafka:
  servers: localhost:9092
  groupID: weixiaobao_group

#kylin:
#  weixiaobao:
#    userName: admin
#    password: KYLIN
#    decrypt: true
#    connectionUrl: jdbc:kylin://ali-hz-data-platform-7:7070/weixiaobao

# distributed lock配置
curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: localhost:2181
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 5000

mysql:
  common:
    userName: root
    passWord: lichao0903
    decrypt: false
    masterUrl: jdbc:mysql://127.0.0.1:3306/kmap?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  bussiness:
    userName: root
    passWord: lichao0903
    decrypt: false
    masterUrl: jdbc:mysql://127.0.0.1:3306/kmap?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false